spring:
  application:
    name: duck_td
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: JDBC
  datasource:
    name: duck_td
    url: jdbc:mysql://localhost:3306/qd?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false&allowMultiQueries=true
    username: root
    #password: 123456
    password: Aa123456.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false #为了热加载
    charset: utf-8
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: true
    settings:
      number_format: 0.## #全局浮点类型的最多可展示2位

server:
  port: 8088
  ctxVal: /
  servlet:
    context-path: /
logging:
  level:
    ROOT: info
  file: qd.log


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  params: pageNum=pageNumKey;pageSize=pageSizeKey;count=countSql
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  page-size-zero: true


